
[window]
opacity = 0.8
dynamic_padding = true
decorations = "Full"
blur = true

[general]
import = [
    "~/.config/alacritty/themes/themes/ayu_dark.toml"
]

[terminal]

[terminal.shell]
program = "/usr/bin/fish"
args = []

